### ISSUE TITLE
Swift command (and maybe others) don't handle paths with spaces

### ISSUE THREAD

**Issue by Imar** [dynamicweb/CLI#4]
I am trying to get the latest Swift files intro a folder containing a space. I execute this command:

dw swift "D:\Some Path" # Note the double quotes around the path

**Expected results:**
Files and folders are stored under "D:\Some Path"

**Actual results:**
Files and folders are stored under "D:\Some"

Tested against today's latest version of the CLI and DW 10 Alpha 8

**Comment by frederik5480** [comment]
This will be fixed with PR #13
