### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by Imar** [dynamicweb/CLI#8]
It seems that the download option is not working or not doing the right thing. I am trying to export the entire system folder to a local folder.

This works:
**dw files -l system** #shows all first level folders under system
**dw files -lf system** #shows all first level folders under system and their direct files
**dw files -lfr system** #shows all folders and files recursively

However, these don't work:
**dw files -fre system** # doesn't download even though e is set. Error: No files found in directory 'system', if you want to download all folders recursively include the -r flag
**dw files -fre system system** #same as previous
**dw files -fre system "D:\Some\system"** #same as previous

It seems that -e with and without -r just doesn't seem to do anything

**Comment by frederik5480** [comment]
This is also cause by the change with our management API and is fixed in PR #12
